// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SprmAuthentication.EFs;

#nullable disable

namespace SprmAuthentication.Migrations
{
    [DbContext(typeof(AuthenticationContext))]
    partial class AuthenticationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SprmAuthentication.Core.AppUsers.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasComment("system id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasColumnOrder(2)
                        .HasComment("Create date");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("create_user")
                        .HasColumnOrder(1)
                        .HasComment("Creator");

                    b.Property<JsonDocument>("CustomValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue(System.Text.Json.JsonDocument.Parse("{}", new System.Text.Json.JsonDocumentOptions()))
                        .HasColumnName("custom_values")
                        .HasComment("自訂屬性值");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("full_name")
                        .HasComment("App使用者姓名");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin")
                        .HasComment("是否為系統管理員");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password")
                        .HasComment("Password hash");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(5)
                        .HasComment("Remarks");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date")
                        .HasColumnOrder(4)
                        .HasComment("Update date");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("update_user")
                        .HasColumnOrder(3)
                        .HasComment("Updator");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username")
                        .HasComment("App使用者名稱");

                    b.HasKey("Id");

                    b.ToTable("app_users", "sprm-auth", t =>
                        {
                            t.HasComment("App使用者");
                        });
                });

            modelBuilder.Entity("SprmAuthentication.Core.Permissions.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(0)
                        .HasComment("system id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasColumnOrder(2)
                        .HasComment("Create date");

                    b.Property<bool>("CreatePermitted")
                        .HasColumnType("boolean")
                        .HasColumnName("create_permitted")
                        .HasComment("允許建立");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("create_user")
                        .HasColumnOrder(1)
                        .HasComment("Creator");

                    b.Property<bool>("DeletePermitted")
                        .HasColumnType("boolean")
                        .HasColumnName("delete_permitted")
                        .HasComment("允許刪除");

                    b.Property<long>("ObjectTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_type_id")
                        .HasComment("物件類型id");

                    b.Property<bool>("ReadPermitted")
                        .HasColumnType("boolean")
                        .HasColumnName("read_permitted")
                        .HasComment("允許讀取");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks")
                        .HasColumnOrder(5)
                        .HasComment("Remarks");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date")
                        .HasColumnOrder(4)
                        .HasComment("Update date");

                    b.Property<bool>("UpdatePermitted")
                        .HasColumnType("boolean")
                        .HasColumnName("update_permitted")
                        .HasComment("允許修改");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("update_user")
                        .HasColumnOrder(3)
                        .HasComment("Updator");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasComment("App使用者id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ObjectTypeId")
                        .IsUnique();

                    b.ToTable("permissions", "sprm-auth", t =>
                        {
                            t.HasComment("權限");
                        });
                });

            modelBuilder.Entity("SprmAuthentication.Core.Permissions.Permission", b =>
                {
                    b.HasOne("SprmAuthentication.Core.AppUsers.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
